# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SearchMovieApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod 'RxSwift', '6.5.0'
    pod 'RxCocoa', '6.5.0'
    pod 'Moya', '~> 15.0'
    pod 'PinLayout'
    pod 'FlexLayout'

  # Pods for SearchMovieApp

  target 'SearchMovieAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SearchMovieAppUITests' do
    # Pods for testing
  end

end
